const ERROR_CODE_WRONG_DATA = 400;
const ERROR_CODE_AUTH = 401;
const ERROR_CODE_FORBIDDEN = 403;
const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_DUPLICATE = 409;

module.exports = {
  ERROR_CODE_WRONG_DATA,
  ERROR_CODE_AUTH,
  ERROR_CODE_FORBIDDEN,
  ERROR_CODE_NOT_FOUND,
  ERROR_CODE_DUPLICATE,
}